{{ if .Values.installRegistryUINginxConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.registryUINginxConfigConfigMapName }}
  labels:
    app: st4sd-registry-ui
    st4sd.ibm.com/component: registry-ui
data:
{{ if .Values.isGlobalRegistry }}
  nginx.conf: |-
    worker_processes auto;
    pid /tmp/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {

      #
      include /etc/nginx/mime.types; 
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;
      
      # Caching
      proxy_cache_path /tmp/cache levels=1:2 keys_zone=backend_cache:10m inactive=60m use_temp_path=off;
      
      # Logging
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /dev/stdout main;
      error_log  /dev/stdout info;

      server {
        listen 8080;
        server_name _;

        index index.html;

        # https://docs.nginx.com/nginx/admin-guide/web-server/compression/
        gzip on;
        # Content types from Network tab
        gzip_types text/html application/javascript text/css application/json image/svg+xml font/woff2;
        gzip_proxied no-cache no-store private expired auth;
        gzip_min_length 1000;
        gzip_http_version 1.0;
        gzip_comp_level 6;
        gzip_vary on;

        location /registry-ui/ {
          rewrite ^/registry-ui/(.*)$ /$1;
        }

        location / {
          root /code;
          try_files $uri /index.html;
        }

        location /backend/ {
          proxy_cache backend_cache;
          proxy_ignore_headers Cache-Control;
          proxy_cache_valid any 10m;
          proxy_cache_lock on;
          proxy_pass http://st4sd-registry-backend:8085/;
        }
      }
    }
{{ else }}
  nginx.conf: |-
    worker_processes auto;
    pid /tmp/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {

      #
      include /etc/nginx/mime.types; 
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;
      
      # Logging
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /dev/stdout main;
      error_log  /dev/stdout info;

      server {
        listen 8080;
        server_name _;

        index index.html;

        # https://docs.nginx.com/nginx/admin-guide/web-server/compression/
        gzip on;
        # Content types from Network tab
        gzip_types text/html application/javascript text/css application/json image/svg+xml font/woff2;
        gzip_proxied no-cache no-store private expired auth;
        gzip_min_length 1000;
        gzip_http_version 1.0;
        gzip_comp_level 6;
        gzip_vary on;
        
        location /registry-ui/ {
          rewrite ^/registry-ui/(.*)$ /$1;
        }

        location / {
          root /code;
          try_files $uri /index.html;
        }

        location /backend/ {
          proxy_pass http://st4sd-registry-backend:8085/;
        }
      }
    }
{{ end }}
{{ end }}