{{ if .Values.installRuntimeService }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
    st4sd.ibm.com/component: oauth-proxy
  name: trusted-certificates-ca
{{ end }}