{{ if .Values.installDatastore }}

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    st4sd.ibm.com/component: datastore
  name: st4sd-datastore-mongodb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: st4sd-datastore-mongodb
    name: st4sd-datastore-mongodb
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    recreateParams: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: st4sd-datastore-mongodb
        name: st4sd-datastore-mongodb
    spec:
      serviceAccountName: {{ .Values.serviceAccountWithSCC }}
      securityContext:
        runAsUser: {{int64 .Values.workflowContainersUid}}
        runAsGroup: {{ int64 .Values.workflowContainersGroupId }}
        fsGroup: {{ int64 .Values.namespaceContainersFsGroupCommon }}
      containers:
      - env:
        - name: LOCATION_DATABASE
          value: {{ printf "%s%s" "/data/db/" .Values.datastoreMongoDBRelativePath }}
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Values.datastoreMongoDBSecretName }}
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Values.datastoreMongoDBSecretName }}
        - name: MONGODB_DATABASE
          value: admin
        image: {{ .Values.imagesDatastoreMongoDB }}{{ .Values.imagesVariant }}
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        resources: {{ toYaml .Values.resources.datastoreMongoDB | nindent 10}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
      dnsPolicy: ClusterFirst
      {{ if .Values.useImagePullSecretWorkflowStack }}
      imagePullSecrets:
        - name: "{{- printf .Values.workflowImagePullSecret }}"
      {{ end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: {{ .Values.pvcForDatastoreMongoDB }}
      
  test: false
  triggers:
  {{ if .Values.useImageStreamTags }}
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongodb
      from:
        kind: ImageStreamTag
        name: {{ .Values.imageStreamTagDatastoreMongoDB }}{{ .Values.imagesVariant }}
    type: ImageChange
  {{ end }}


{{ end }}
