{{ if and .Values.imagesVariant .Values.installDatastore }}

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: datastore
    st4sd.ibm.com/component: datastore
  name: {{ .Values.imageStreamTagDatastore}}
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: {{ .Values.imagesDatastore }}{{ .Values.imagesVariant }}
    importPolicy: {}
    name: {{ .Values.imagesVariant }}
    reference: true
    referencePolicy:
      type: Source

{{ end }}