{{ if and .Values.imagesVariant .Values.installDatastore }}

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: st4sd-datastore-mongodb
    st4sd.ibm.com/component: datastore-mongodb
  name: {{ .Values.imageStreamTagDatastoreMongoDB }}
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: {{ .Values.imagesDatastoreMongoDB }}{{ .Values.imagesVariant }}
    importPolicy: {}
    name: {{ .Values.imagesVariant }}
    reference: true
    referencePolicy:
      type: Source

{{ end }}