{{ if and .Values.installRegistryUI .Values.isGlobalRegistry}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: st4sd-registry-ui
    st4sd.ibm.com/component: registry-ui
  name: st4sd-registry-ui
spec:
  # host: {{ include "host.workflowStack" . }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: st4sd-registry-ui
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None
{{ end }}