{{ if .Values.installImagePullSecretWorkflowStack }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.workflowImagePullSecret }}
data:
  #VV: If you are using DEBUG=yes what you see below does not include what's on the server.
  # Helm will not contact the server when not actually deploying.
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imagePullSecretWorkflowStackRegistryURL (printf "%s:%s" .Values.imagePullSecretWorkflowStackUsername .Values.imagePullSecretWorkflowStackPassword | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson

{{ end }}