{{ if .Values.installImagePullSecretContribApplications }}

# Use imagePullSecretWorkflowStackUsername if imagePullSecretContribApplicationsUsername is undefined
# ditto for imagePullSecretWorkflowStackPassword and imagePullSecretContribApplicationsPassword

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.contribApplicationsImagePullSecret }}
data:
  .dockerconfigjson: {{
    printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imagePullSecretContribApplicationsRegistryURL (printf "%s:%s" (default .Values.imagePullSecretWorkflowStackUsername .Values.imagePullSecretContribApplicationsUsername) (default .Values.imagePullSecretWorkflowStackPassword .Values.imagePullSecretContribApplicationsPassword) | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson

{{ end }}