{{ if .Values.installGithubSecretOAuth }}

apiVersion: v1
data:
  oauth-token: {{ print .Values.gitOAuthToken | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.gitOAuthSecretName | quote }}
type: Opaque


{{ end }}