{{ if .Values.installDatastoreSecretMongoDB }}

apiVersion: v1
data:
  #VV: If you are using DEBUG=yes what you see below does not include what's on the server.
  # Helm will not contact the server when not actually deploying.
  password: {{ (include "secrets.databaseMongoUserPassSecret" .) }}
  username: {{ print "admin" | b64enc | quote }}
kind: Secret
metadata:
  labels: 
    st4sd.ibm.com/component: datastore
  name: {{ .Values.datastoreMongoDBSecretName }}
type: Opaque

{{ end }}