{{ if .Values.installAuthentication }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauthProxySeedSecretName }}
data:
  #VV: If you are using DEBUG=yes what you see below does not include what's on the server.
  # Helm will not contact the server when not actually deploying.
  session_secret: {{ (include "secrets.authenticationSeed" .) }}
type: Opaque

{{ end }}