{{ if .Values.installImagePullSecretCommunityApplications }}

# Use imagePullSecretWorkflowStackUsername if imagePullSecretCommunityApplicationsUsername is undefined
# ditto for imagePullSecretWorkflowStackPassword and imagePullSecretCommunityApplicationsPassword

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.communityApplicationsImagePullSecret }}
data:
  .dockerconfigjson: {{
    printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imagePullSecretCommunityApplicationsRegistryURL (printf "%s:%s" (default .Values.imagePullSecretWorkflowStackUsername .Values.imagePullSecretCommunityApplicationsUsername) (default .Values.imagePullSecretWorkflowStackPassword .Values.imagePullSecretCommunityApplicationsPassword) | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson

{{ end }}