{{ if .Values.installRuntimeService }}
apiVersion: v1
kind: Service
metadata:
  labels:
    st4sd.ibm.com/component: runtime-service
  name: st4sd-runtime-service

spec:
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: st4sd-runtime-service
  sessionAffinity: None
  type: ClusterIP
{{ end }}