{{ if .Values.installDatastore }}

apiVersion: v1
kind: Service
metadata:
  labels:
    st4sd.ibm.com/component: datastore
  name: st4sd-datastore-cloud-instance
spec:
  ports:
  - name: cluster-gateway
    port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: st4sd-datastore-cloud-instance
  sessionAffinity: None
  type: ClusterIP

{{ end }}