{{ if .Values.installDatastore }}

apiVersion: v1
kind: Service
metadata:
  labels:
    st4sd.ibm.com/component: datastore
  name: st4sd-datastore-mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: st4sd-datastore-mongodb
  sessionAffinity: None
  type: ClusterIP

{{ end }}