{{ if .Values.installRegistryBackend }}
apiVersion: v1
kind: Service
metadata:
  labels:
    st4sd.ibm.com/component: registry-backend
  name: st4sd-registry-backend

spec:
  selector:
    app: st4sd-registry-backend
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
{{ end }}